---
title: "MCM_2022"
author: "MCM2022"
date: "2/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(keras)
library(caret)
library(ggforce)

#install_keras()

theme_set(theme_minimal())

set.seed(123)
```

```{r}
# Load the data & clean the data
bitcoin_data <- read.csv("data/BCHAIN-MKPRU.csv") %>% 
  mutate(Date = as.Date(Date, "%m/%d/%y")) %>% 
  na.omit()

gold_data <- read.csv("data/LBMA-GOLD.csv") %>% 
  mutate(Date = as.Date(Date, "%m/%d/%y")) %>% 
  na.omit()
```

```{r}
bitcoin_matrix <- as.matrix(bitcoin_data$Value)
diffed = diff(bitcoin_matrix, differences = 1)
head(diffed)
```

```{r}
# Visualize data
lag_transform <- function(x, k= 1){
    
      lagged =  c(rep(NA, k), x[1:(length(x)-k)])
      DF = as.data.frame(cbind(lagged, x))
      colnames(DF) <- c( paste0('x-', k), 'x')
      DF[is.na(DF)] <- 0
      return(DF)
}
supervised = lag_transform(diffed, 1)
head(supervised)
```

```{r}
## split into train and test sets
N = nrow(supervised)
n = 1460
train = supervised[1:n, ]
test  = supervised[(n+1):N,  ]
```

```{r}
## scale data
scale_data = function(train, test, feature_range = c(0, 1)) {
  x = train
  fr_min = feature_range[1]
  fr_max = feature_range[2]
  std_train = ((x - min(x) ) / (max(x) - min(x)  ))
  std_test  = ((test - min(x) ) / (max(x) - min(x)  ))
  
  scaled_train = std_train *(fr_max -fr_min) + fr_min
  scaled_test = std_test *(fr_max -fr_min) + fr_min
  
  return( list(scaled_train = as.vector(scaled_train), scaled_test = as.vector(scaled_test) ,scaler= c(min =min(x), max = max(x))) )
  
}


Scaled = scale_data(train, test, c(-1, 1))

y_train = Scaled$scaled_train[, 2]
x_train = Scaled$scaled_train[, 1]

y_test = Scaled$scaled_test[, 2]
x_test = Scaled$scaled_test[, 1]
```

```{r}
## inverse-transform
invert_scaling = function(scaled, scaler, feature_range = c(0, 1)){
  min = scaler[1]
  max = scaler[2]
  t = length(scaled)
  mins = feature_range[1]
  maxs = feature_range[2]
  inverted_dfs = numeric(t)
  
  for( i in 1:t){
    X = (scaled[i]- mins)/(maxs - mins)
    rawValues = X *(max - min) + min
    inverted_dfs[i] <- rawValues
  }
  return(inverted_dfs)
}
```

```{r}
# Reshape the input to 3-dim
dim(x_train) <- c(length(x_train), 1, 1)

# specify required arguments
X_shape2 = dim(x_train)[2]
X_shape3 = dim(x_train)[3]
batch_size = 146 # must be a common factor of both the train and test samples
units = 60 # can adjust this, in model tuning phase

model <- keras_model_sequential() 
model%>%
  layer_lstm(units, batch_input_shape = c(batch_size, X_shape2, X_shape3), stateful= TRUE)%>%
  layer_dense(units = 1)
```

```{r}
model %>% compile(
  loss = 'mean_squared_error',
  optimizer = "adam")
```

```{r}
summary(model)
```

```{r}
Epochs = 15
#for(i in 1:Epochs ){
#  model %>% fit(x_train, y_train, epochs=1, batch_size=batch_size, verbose=1, shuffle=FALSE)
#  model %>% reset_states()
#}
trained_model <- model %>% fit(
    x = x_train, # sequence we're using for prediction 
    y = y_train, # sequence we're predicting
    batch_size = batch_size, # how many samples to pass to our model at a time
    epochs = Epochs, # how many times we'll look @ the whole dataset
    validation_split = 0.2) # how much data to hold out for testing as we go along

plot(trained_model)
```

```{r}
L = length(x_test)
scaler = Scaled$scaler
predictions = numeric(L)

for(i in 1:L){
     X = x_test[i]
     dim(X) = c(1,1,1)
     yhat = model %>% predict(X, batch_size=batch_size)
     # invert scaling
     yhat = invert_scaling(yhat, scaler,  c(-1, 1))
     # invert difference
     yhat = yhat + bitcoin_matrix[(n+i)]
     # store
     predictions[i] <- yhat
}
```

```{r, fig.width=10,fig.height=3}
bitcoin_predicted <- bitcoin_data %>% 
  slice((n+2):1826) %>% 
  mutate(predicted = predictions) %>% 
  mutate(dif = abs(predicted - Value))

bitcoin_predicted

bitcoin_data_new <- bitcoin_data %>% 
  slice((n+2):1826)

ggplot() +
  geom_line(data = bitcoin_data_new, aes(x = Date, y = Value), color = "blue") +
  geom_line(data = bitcoin_predicted, aes(x = Date, y = predicted), color = "red")

ggplot() +
  geom_line(data = bitcoin_predicted, aes(x = Date, y = dif))
```







