---
title: "MCM_2022"
author: "MCM2022"
date: "2/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(keras)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(lubridate)
#install_keras()

theme_set(theme_minimal())

set.seed(123)
```

```{r}
# Load the data & clean the data
bitcoin_data <- read.csv("data/BCHAIN-MKPRU.csv") %>%
  mutate(Date = as.Date(Date, "%m/%d/%y")) %>%
  na.omit()
gold_data <- read.csv("data/LBMA-GOLD.csv") %>%
  mutate(Date = as.Date(Date, "%m/%d/%y")) %>%
  na.omit()

lstm_model <- readRDS("lstm_model.rds")
```

```{r}
makeReadable <- function(numList, look_back)
{
  max_value <- max(numList)
  min_value <- min(numList)
  spread <- max_value - min_value
  dataset <- (numList - min_value) / spread
  l <- length(dataset)
  dataX <- array(dim = c(l - look_back, look_back))
  
  for (i in 1:ncol(dataX))
  {
    dataX[, i] <- dataset[i:(l - look_back + i - 1)]
  }
  
  dataY <- array(data = dataset[(look_back + 1):l],
                 dim = c(l - look_back, 1))
  
  return(list(dataX = dataX,
              dataY = dataY))
}

```

```{r}
trainXY <- makeReadable(gold_data$USD..PM., 5)
```

```{r}
# Fit the model to get predicted value
trainPredict <- lstm_model %>%
  predict(trainXY$dataX,
          verbose = 1)
testPredict <- lstm_model %>%
  predict(testXY$dataX,
          verbose = 1)

trainPredict <- trainPredict * spread + min_value
testPredict <- testPredict * spread + min_value
```

```{r}
# Plot the output
df <- data.frame(
  index = 1:length(dataset),
  value = dataset * spread + min_value,
  type = 'raw'
) %>%
  rbind(data.frame(
    index = 1:length(trainPredict) + look_back,
    value = trainPredict,
    type = 'train'
  )) %>%
  rbind(data.frame(
    index = 1:length(testPredict) + look_back + length(train),
    value = testPredict,
    type = 'test'
  ))

ggplot(data = df) +
  geom_line(mapping = aes(x = index,
                          y = value,
                          color = type)) +
  geom_vline(xintercept = length(train) + 0.5) +
  theme_minimal()
```

```{r}
# Save the model
saveRDS(trained_model, "LSTM_model.dep")
```



```{r}
trainPredict <- model %>%
  predict(trainXY$dataX)
testPredict <- model %>%
  predict(testXY$dataX)

trainPredict <- trainPredict * spread + min_value
testPredict <- testPredict * spread + min_value
```

```{r}



df1 <- df %>% 
  filter(index >= 0,
         index < 8) 

ggplot(data = df1) +
  geom_line(mapping = aes(x = index,
                          y = value,
                          color = type)) +
  theme_minimal()
```


